### ISSUE TITLE
Outdated setup wizard

### ISSUE THREAD

**Issue by Xartrick** [EDM-Spot/OtterBot#3]
## Steps to reproduce

* Clone this repository
* Run `npm install`
* Configure using wizard
* Run `npm run start`

```
λ  OtterBot master ✓ npm install

[...]

> otterbot@1.0.3 postinstall /home/xartrick/dev/xartrick/OtterBot
> node util/setup.js

Setting Up GuideBot Configuration... CTRL+C if you want to manually edit config.js.example into config.js!
First Start! Inserting default guild settings in the database...
Are you hosted on Glitch.com? [y/n]: n
Enter the bot token from the application page: [hidden]
Enter the Client Secret from the application page: [hidden]
Enter a session security passphrase (used to encrypt session data): [hidden]
Please enter your domain name (no http prefix, port optional, e.g. localhost:8080 or www.example.com): localhost:8082
Enter the port on which to start the local server (default 81): 8082
REMEMBER TO NEVER SHARE YOUR TOKEN WITH ANYONE!
Configuration has been written, enjoy!
added 493 packages from 360 contributors and audited 995 packages in 317.077s
found 0 vulnerabilities
```

```
λ  OtterBot master ✗ npm run start 

> otterbot@1.0.3 start /home/xartrick/dev/xartrick/OtterBot
> node index.js

/home/xartrick/dev/xartrick/OtterBot/index.js:36
    this.Redis = new Redis(this.config.db.redis);
                                          ^

TypeError: Cannot read property 'redis' of undefined
    at new Bot (/home/xartrick/dev/xartrick/OtterBot/index.js:36:43)
    at Object.<anonymous> (/home/xartrick/dev/xartrick/OtterBot/index.js:223:16)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! otterbot@1.0.3 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the otterbot@1.0.3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/xartrick/.npm/_logs/2018-10-28T20_33_24_821Z-debug.log
```
## Wordaround

* Skip wizard and edit `config.js.example` to `config.js`

## Solution

* Update `util/setup.js` and `util/setup_base.txt` to current version

**Comment by Xartrick** [comment]
Fixed in #7.
