### ISSUE TITLE
Dashboard won't load if no song is playing

### ISSUE THREAD

**Issue by Xartrick** [EDM-Spot/OtterBot#5]
## Steps to reproduce

* Clone this repository
* Run `npm install`
* Edit `config.js.example` to `config.js`
* Run `npm run start`
* Go to website

```
TypeError: Cannot read property 'cid' of undefined
    at PlugAPI.run (/home/xartrick/dev/xartrick/OtterBot/plugModules/events/plug/advance.js:143:28)
```

```
TypeError: /home/xartrick/dev/xartrick/OtterBot/dashboard/templates/index.ejs:24
    22|           <div class="col-md-6">
    23|             <h4>Now Playing:</h4>
 >> 24|             <iframe id="ytplayer" type="text/html" src="https://www.youtube.com/embed/<%= bot.plug.getMedia().cid %>"
    25|               frameborder="0" height="300" width="500"></iframe>
    26|           </div>
    27|           <div class="col-md-6">

Cannot read property 'cid' of undefined
    at eval (eval at compile (/home/xartrick/dev/xartrick/OtterBot/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:24:45)
    at returnedFn (/home/xartrick/dev/xartrick/OtterBot/node_modules/ejs/lib/ejs.js:653:17)
    at tryHandleCache (/home/xartrick/dev/xartrick/OtterBot/node_modules/ejs/lib/ejs.js:251:36)
    at View.exports.renderFile [as engine] (/home/xartrick/dev/xartrick/OtterBot/node_modules/ejs/lib/ejs.js:482:10)
    at View.render (/home/xartrick/dev/xartrick/OtterBot/node_modules/express/lib/view.js:135:8)
    at tryRender (/home/xartrick/dev/xartrick/OtterBot/node_modules/express/lib/application.js:640:10)
    at Function.render (/home/xartrick/dev/xartrick/OtterBot/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/home/xartrick/dev/xartrick/OtterBot/node_modules/express/lib/response.js:1008:7)
    at renderTemplate (/home/xartrick/dev/xartrick/OtterBot/util/dashboard.js:167:9)
    at app.get (/home/xartrick/dev/xartrick/OtterBot/util/dashboard.js:303:5)
```

## Workaround

* Play a song :)

## Solution

* Check if `bot.plug.getMedia()` is not `undefined`

**Comment by Xartrick** [comment]
Fixed in #6.
